### ISSUE TITLE
Release pre-trained model for TSN feature

### ISSUE THREAD

**Issue by anh-ntv** [ttengwang/ESGN#2]
Hi, thank you for publishing this great code.
I am producing your result in the project [dense-video-captioning-pytorch](https://github.com/ttengwang/dense-video-captioning-pytorch)
In your paper, you only mention TSN feature. However, you only published a pre-trained model of ESGN for the C3D feature. Can you publish pre-trained for TSN feature as well?

**Comment by ttengwang** [comment]
@anh-ntv  Thanks for your attention to our work. I will release it a few days later.

**Comment by ttengwang** [comment]
Hi, I upload a pre-trained model for TSN features (3072d, same as [dense-video-captioning-pytorch](https://github.com/ttengwang/dense-video-captioning-pytorch)) at [google drive](https://drive.google.com/drive/folders/16hecaHsH1p9Wj206tOADkYqQdvyp_WKH?usp=sharing). This model gives  Precision/Recall=67.15/37.80 with reranking and 58.66/53.43 without reranking.
